extends: idiomatic
root: true
env:
  node: true
  browser: true
rules:
  no-console: off
  func-names: 0
  comma-dangle:
    - error
    - always-multiline
  semi:
    - error
    - always
parserOptions:
  sourceType: module
